<Project>
  <!-- These common settings only apply to C# projects. -->
  <PropertyGroup>
    <!-- Configure C# language properties -->
    <TargetFramework>net10.0-windows</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
    <DebugType>embedded</DebugType>

    <!-- Code Analysis -->
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>

    <!-- Redirect output directories -->
    <UseArtifactsOutput>true</UseArtifactsOutput>
    <ArtifactsPath>$(MSBuildThisFileDirectory)../Build</ArtifactsPath>

    <!-- Only selected projects will generate a NuGet package -->
    <IsPackable>false</IsPackable>
    <IsPublishable>false</IsPublishable>
    <EnablePackageValidation>true</EnablePackageValidation>

    <!-- Use lock files to enable NuGet package caching at GitHub -->
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>
</Project>
