name: Release
run-name: 'Release ${{ github.run_number }}'

permissions:
  id-token: write
  contents: write

on: workflow_dispatch

jobs:
  build:
    name: 'Build'
    runs-on: windows-latest
    timeout-minutes: 10
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v6

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        cache: true
        cache-dependency-path: 'Src/*/packages.lock.json'

    - name: Restore NuGet Packages
      run: dotnet restore --use-lock-file

    - name: Build and Publish Injector x64
      run: dotnet publish Src/SpecterOps.Passkeys.Injector --runtime win-x64 --no-restore

    - name: Build and Publish Injector ARM64
      run: dotnet publish Src/SpecterOps.Passkeys.Injector --runtime win-arm64 --no-restore

    - name: Build Mythic CLI
      run: dotnet build Src/SpecterOps.Passkeys.Mythic --configuration Release --no-restore

    - name: Extract Versions
      id: versions
      shell: pwsh
      run: |
        [string]$injector = (Select-Xml -Path 'Src/SpecterOps.Passkeys.Injector/SpecterOps.Passkeys.Injector.csproj' -XPath '//Version').Node.InnerText
        [string]$mythic = (Select-Xml -Path 'Src/SpecterOps.Passkeys.Mythic/SpecterOps.Passkeys.Mythic.csproj' -XPath '//Version').Node.InnerText
        "INJECTOR_VERSION=$injector" >> $env:GITHUB_OUTPUT
        "MYTHIC_VERSION=$mythic" >> $env:GITHUB_OUTPUT

    - name: Upload x64 Binary as Artifact
      uses: actions/upload-artifact@v6
      with:
        name: PasskeyInjector_v${{ steps.versions.outputs.INJECTOR_VERSION }}_x64
        path: Build/publish/SpecterOps.Passkeys.Injector/release_win-x64/*

    - name: Upload ARM64 Binary as Artifact
      uses: actions/upload-artifact@v6
      with:
        name: PasskeyInjector_v${{ steps.versions.outputs.INJECTOR_VERSION }}_arm64
        path: Build/publish/SpecterOps.Passkeys.Injector/release_win-arm64/*

    - name: Upload Mythic CLI as Artifact
      uses: actions/upload-artifact@v6
      with:
        name: PasskeysMythicCLI_v${{ steps.versions.outputs.MYTHIC_VERSION }}
        path: Build/bin/SpecterOps.Passkeys.Mythic/release/*

    - name: Create GitHub Release
      shell: pwsh
      working-directory: Build
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        @'
        ### Notable Changes

        '@ > release-notes.md
        gh release create v${{ steps.versions.outputs.INJECTOR_VERSION }} publish/SpecterOps.Passkeys.Injector/**/*.exe bin/SpecterOps.Passkeys.Mythic/release/*.exe --draft --latest --title "Passkey Injector ${{ steps.versions.outputs.INJECTOR_VERSION }}" --notes-file release-notes.md
